using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WestPacificUniversity.Data.Entities;

[Table("Courses")]
public class Course
{
    /// <summary>
    /// Each course has its own assigned course number. And course number isn't generated by database.
    /// </summary>
    [Display(Name = "Course Number")]
    [DatabaseGenerated(DatabaseGeneratedOption.None)]
    public int CourseId { get; set; }

    [Display(Name = "Course Name")]
    [StringLength(100, MinimumLength = 3)]
    public string Title { get; set; } = default!;

    [Range(0, 5)]
    public int Credit { get; set; }

    // What if we delete the department entity? - do not do cascade deletion (specified in context)
    // Ideally we should set it nullable.
    public int DepartmentId { get; set; }
    // The navigation property must be nullable (for being used as edit/create DTO)
    // (By default, non-nullable property is required)
    public Department? Department { get; set; } = default!;

    /// <summary>
    /// Many-to-many relationship to <see cref="Student"/>.
    /// </summary>
    public ICollection<Enrollment>? Enrollments { get; set; }

    /// <summary>
    /// Many-to-many relationship to <see cref="Instructor"/>.
    /// </summary>
    public ICollection<CourseAssignment>? CourseAssignments { get; set; }
}
